/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Camera model module.
 * @module model/Camera
 * @version 1.0.0
 */
class Camera {
    /**
     * Constructs a new <code>Camera</code>.
     * A camera input object
     * @alias module:model/Camera
     * @param name {String} 
     * @param created {String} 
     * @param cameraType {Number} 
     * @param streamName {String} 
     * @param status {Number} 
     */
    constructor(name, created, cameraType, streamName, status) { 
        
        Camera.initialize(this, name, created, cameraType, streamName, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, created, cameraType, streamName, status) { 
        obj['name'] = name;
        obj['created'] = created;
        obj['cameraType'] = cameraType;
        obj['streamName'] = streamName;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>Camera</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Camera} obj Optional instance to populate.
     * @return {module:model/Camera} The populated <code>Camera</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Camera();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('cameraType')) {
                obj['cameraType'] = ApiClient.convertToType(data['cameraType'], 'Number');
            }
            if (data.hasOwnProperty('streamName')) {
                obj['streamName'] = ApiClient.convertToType(data['streamName'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Camera.prototype['name'] = undefined;

/**
 * @member {String} created
 */
Camera.prototype['created'] = undefined;

/**
 * @member {Number} cameraType
 */
Camera.prototype['cameraType'] = undefined;

/**
 * @member {String} streamName
 */
Camera.prototype['streamName'] = undefined;

/**
 * @member {Number} status
 */
Camera.prototype['status'] = undefined;






export default Camera;

