/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CameraCapture model module.
 * @module model/CameraCapture
 * @version 1.0.0
 */
class CameraCapture {
    /**
     * Constructs a new <code>CameraCapture</code>.
     * A camera capture input object.
     * @alias module:model/CameraCapture
     * @param cameraId {Number} 
     * @param created {String} 
     * @param personCount {Number} 
     * @param density {Number} 
     */
    constructor(cameraId, created, personCount, density) { 
        
        CameraCapture.initialize(this, cameraId, created, personCount, density);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, created, personCount, density) { 
        obj['cameraId'] = cameraId;
        obj['created'] = created;
        obj['personCount'] = personCount;
        obj['density'] = density;
    }

    /**
     * Constructs a <code>CameraCapture</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CameraCapture} obj Optional instance to populate.
     * @return {module:model/CameraCapture} The populated <code>CameraCapture</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CameraCapture();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('personCount')) {
                obj['personCount'] = ApiClient.convertToType(data['personCount'], 'Number');
            }
            if (data.hasOwnProperty('density')) {
                obj['density'] = ApiClient.convertToType(data['density'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
CameraCapture.prototype['cameraId'] = undefined;

/**
 * @member {String} created
 */
CameraCapture.prototype['created'] = undefined;

/**
 * @member {Number} personCount
 */
CameraCapture.prototype['personCount'] = undefined;

/**
 * @member {Number} density
 */
CameraCapture.prototype['density'] = undefined;






export default CameraCapture;

