/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CameraTimeSpent model module.
 * @module model/CameraTimeSpent
 * @version 1.0.0
 */
class CameraTimeSpent {
    /**
     * Constructs a new <code>CameraTimeSpent</code>.
     * A time spent object.
     * @alias module:model/CameraTimeSpent
     * @param cameraId {Number} 
     * @param captureStart {String} 
     * @param estTimeSpent {Number} 
     */
    constructor(cameraId, captureStart, estTimeSpent) { 
        
        CameraTimeSpent.initialize(this, cameraId, captureStart, estTimeSpent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, captureStart, estTimeSpent) { 
        obj['cameraId'] = cameraId;
        obj['captureStart'] = captureStart;
        obj['estTimeSpent'] = estTimeSpent;
    }

    /**
     * Constructs a <code>CameraTimeSpent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CameraTimeSpent} obj Optional instance to populate.
     * @return {module:model/CameraTimeSpent} The populated <code>CameraTimeSpent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CameraTimeSpent();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('captureStart')) {
                obj['captureStart'] = ApiClient.convertToType(data['captureStart'], 'String');
            }
            if (data.hasOwnProperty('estTimeSpent')) {
                obj['estTimeSpent'] = ApiClient.convertToType(data['estTimeSpent'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
CameraTimeSpent.prototype['cameraId'] = undefined;

/**
 * @member {String} captureStart
 */
CameraTimeSpent.prototype['captureStart'] = undefined;

/**
 * @member {Number} estTimeSpent
 */
CameraTimeSpent.prototype['estTimeSpent'] = undefined;






export default CameraTimeSpent;

