/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CameraBuildConfig model module.
 * @module model/CameraBuildConfig
 * @version 1.0.0
 */
class CameraBuildConfig {
    /**
     * Constructs a new <code>CameraBuildConfig</code>.
     * A build configuration associated with a cameras physical install.
     * @alias module:model/CameraBuildConfig
     * @param cameraId {Number} 
     * @param lat {Number} 
     * @param lng {Number} 
     * @param height {Number} 
     * @param angle {Number} 
     */
    constructor(cameraId, lat, lng, height, angle) { 
        
        CameraBuildConfig.initialize(this, cameraId, lat, lng, height, angle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, lat, lng, height, angle) { 
        obj['cameraId'] = cameraId;
        obj['lat'] = lat;
        obj['lng'] = lng;
        obj['height'] = height;
        obj['angle'] = angle;
    }

    /**
     * Constructs a <code>CameraBuildConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CameraBuildConfig} obj Optional instance to populate.
     * @return {module:model/CameraBuildConfig} The populated <code>CameraBuildConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CameraBuildConfig();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('angle')) {
                obj['angle'] = ApiClient.convertToType(data['angle'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
CameraBuildConfig.prototype['cameraId'] = undefined;

/**
 * @member {Number} lat
 */
CameraBuildConfig.prototype['lat'] = undefined;

/**
 * @member {Number} lng
 */
CameraBuildConfig.prototype['lng'] = undefined;

/**
 * @member {Number} height
 */
CameraBuildConfig.prototype['height'] = undefined;

/**
 * @member {Number} angle
 */
CameraBuildConfig.prototype['angle'] = undefined;






export default CameraBuildConfig;

