/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CameraWalkingPace model module.
 * @module model/CameraWalkingPace
 * @version 1.0.0
 */
class CameraWalkingPace {
    /**
     * Constructs a new <code>CameraWalkingPace</code>.
     * A walking pace object.
     * @alias module:model/CameraWalkingPace
     * @param cameraId {Number} 
     * @param captureStart {String} 
     * @param avgPersonSpeed {Number} 
     */
    constructor(cameraId, captureStart, avgPersonSpeed) { 
        
        CameraWalkingPace.initialize(this, cameraId, captureStart, avgPersonSpeed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, captureStart, avgPersonSpeed) { 
        obj['cameraId'] = cameraId;
        obj['captureStart'] = captureStart;
        obj['avgPersonSpeed'] = avgPersonSpeed;
    }

    /**
     * Constructs a <code>CameraWalkingPace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CameraWalkingPace} obj Optional instance to populate.
     * @return {module:model/CameraWalkingPace} The populated <code>CameraWalkingPace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CameraWalkingPace();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('captureStart')) {
                obj['captureStart'] = ApiClient.convertToType(data['captureStart'], 'String');
            }
            if (data.hasOwnProperty('avgPersonSpeed')) {
                obj['avgPersonSpeed'] = ApiClient.convertToType(data['avgPersonSpeed'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
CameraWalkingPace.prototype['cameraId'] = undefined;

/**
 * @member {String} captureStart
 */
CameraWalkingPace.prototype['captureStart'] = undefined;

/**
 * @member {Number} avgPersonSpeed
 */
CameraWalkingPace.prototype['avgPersonSpeed'] = undefined;






export default CameraWalkingPace;

