/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InsightsGeneratorConfig model module.
 * @module model/InsightsGeneratorConfig
 * @version 1.0.0
 */
class InsightsGeneratorConfig {
    /**
     * Constructs a new <code>InsightsGeneratorConfig</code>.
     * A config object for the insights generator algorithm
     * @alias module:model/InsightsGeneratorConfig
     * @param cameraId {Number} 
     * @param streamName {String} 
     * @param resolutionWidth {Number} 
     * @param resolutionHeight {Number} 
     * @param cornerMaskX1 {Number} 
     * @param cornerMaskY1 {Number} 
     * @param cornerMaskX2 {Number} 
     * @param cornerMaskY2 {Number} 
     * @param cornerMaskX3 {Number} 
     * @param cornerMaskY3 {Number} 
     * @param cornerMaskX4 {Number} 
     * @param cornerMaskY4 {Number} 
     * @param minPointsInPath {Number} 
     * @param writePathsToDynamo {Number} 
     * @param roundPlaces {Number} 
     * @param maxSnakeLen {Number} 
     * @param heatmapColumns {Number} 
     * @param countLineX1 {Number} 
     * @param countLineY1 {Number} 
     * @param countLineX2 {Number} 
     * @param countLineY2 {Number} 
     * @param transformationShapeWidth {Number} 
     * @param transformationShapeHeight {Number} 
     * @param cameraRoiLength {Number} 
     * @param roiGroundCoverage {Number} 
     * @param speedDivider {Number} 
     * @param socialDistanceGuideline {Number} 
     * @param clearPathsFrameInterval {Number} 
     */
    constructor(cameraId, streamName, resolutionWidth, resolutionHeight, cornerMaskX1, cornerMaskY1, cornerMaskX2, cornerMaskY2, cornerMaskX3, cornerMaskY3, cornerMaskX4, cornerMaskY4, minPointsInPath, writePathsToDynamo, roundPlaces, maxSnakeLen, heatmapColumns, countLineX1, countLineY1, countLineX2, countLineY2, transformationShapeWidth, transformationShapeHeight, cameraRoiLength, roiGroundCoverage, speedDivider, socialDistanceGuideline, clearPathsFrameInterval) { 
        
        InsightsGeneratorConfig.initialize(this, cameraId, streamName, resolutionWidth, resolutionHeight, cornerMaskX1, cornerMaskY1, cornerMaskX2, cornerMaskY2, cornerMaskX3, cornerMaskY3, cornerMaskX4, cornerMaskY4, minPointsInPath, writePathsToDynamo, roundPlaces, maxSnakeLen, heatmapColumns, countLineX1, countLineY1, countLineX2, countLineY2, transformationShapeWidth, transformationShapeHeight, cameraRoiLength, roiGroundCoverage, speedDivider, socialDistanceGuideline, clearPathsFrameInterval);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, streamName, resolutionWidth, resolutionHeight, cornerMaskX1, cornerMaskY1, cornerMaskX2, cornerMaskY2, cornerMaskX3, cornerMaskY3, cornerMaskX4, cornerMaskY4, minPointsInPath, writePathsToDynamo, roundPlaces, maxSnakeLen, heatmapColumns, countLineX1, countLineY1, countLineX2, countLineY2, transformationShapeWidth, transformationShapeHeight, cameraRoiLength, roiGroundCoverage, speedDivider, socialDistanceGuideline, clearPathsFrameInterval) { 
        obj['cameraId'] = cameraId;
        obj['streamName'] = streamName;
        obj['resolutionWidth'] = resolutionWidth;
        obj['resolutionHeight'] = resolutionHeight;
        obj['cornerMaskX1'] = cornerMaskX1;
        obj['cornerMaskY1'] = cornerMaskY1;
        obj['cornerMaskX2'] = cornerMaskX2;
        obj['cornerMaskY2'] = cornerMaskY2;
        obj['cornerMaskX3'] = cornerMaskX3;
        obj['cornerMaskY3'] = cornerMaskY3;
        obj['cornerMaskX4'] = cornerMaskX4;
        obj['cornerMaskY4'] = cornerMaskY4;
        obj['minPointsInPath'] = minPointsInPath;
        obj['writePathsToDynamo'] = writePathsToDynamo;
        obj['roundPlaces'] = roundPlaces;
        obj['maxSnakeLen'] = maxSnakeLen;
        obj['heatmapColumns'] = heatmapColumns;
        obj['countLineX1'] = countLineX1;
        obj['countLineY1'] = countLineY1;
        obj['countLineX2'] = countLineX2;
        obj['countLineY2'] = countLineY2;
        obj['transformationShapeWidth'] = transformationShapeWidth;
        obj['transformationShapeHeight'] = transformationShapeHeight;
        obj['cameraRoiLength'] = cameraRoiLength;
        obj['roiGroundCoverage'] = roiGroundCoverage;
        obj['speedDivider'] = speedDivider;
        obj['socialDistanceGuideline'] = socialDistanceGuideline;
        obj['clearPathsFrameInterval'] = clearPathsFrameInterval;
    }

    /**
     * Constructs a <code>InsightsGeneratorConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsightsGeneratorConfig} obj Optional instance to populate.
     * @return {module:model/InsightsGeneratorConfig} The populated <code>InsightsGeneratorConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsightsGeneratorConfig();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('streamName')) {
                obj['streamName'] = ApiClient.convertToType(data['streamName'], 'String');
            }
            if (data.hasOwnProperty('resolutionWidth')) {
                obj['resolutionWidth'] = ApiClient.convertToType(data['resolutionWidth'], 'Number');
            }
            if (data.hasOwnProperty('resolutionHeight')) {
                obj['resolutionHeight'] = ApiClient.convertToType(data['resolutionHeight'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskX1')) {
                obj['cornerMaskX1'] = ApiClient.convertToType(data['cornerMaskX1'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskY1')) {
                obj['cornerMaskY1'] = ApiClient.convertToType(data['cornerMaskY1'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskX2')) {
                obj['cornerMaskX2'] = ApiClient.convertToType(data['cornerMaskX2'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskY2')) {
                obj['cornerMaskY2'] = ApiClient.convertToType(data['cornerMaskY2'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskX3')) {
                obj['cornerMaskX3'] = ApiClient.convertToType(data['cornerMaskX3'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskY3')) {
                obj['cornerMaskY3'] = ApiClient.convertToType(data['cornerMaskY3'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskX4')) {
                obj['cornerMaskX4'] = ApiClient.convertToType(data['cornerMaskX4'], 'Number');
            }
            if (data.hasOwnProperty('cornerMaskY4')) {
                obj['cornerMaskY4'] = ApiClient.convertToType(data['cornerMaskY4'], 'Number');
            }
            if (data.hasOwnProperty('minPointsInPath')) {
                obj['minPointsInPath'] = ApiClient.convertToType(data['minPointsInPath'], 'Number');
            }
            if (data.hasOwnProperty('writePathsToDynamo')) {
                obj['writePathsToDynamo'] = ApiClient.convertToType(data['writePathsToDynamo'], 'Number');
            }
            if (data.hasOwnProperty('roundPlaces')) {
                obj['roundPlaces'] = ApiClient.convertToType(data['roundPlaces'], 'Number');
            }
            if (data.hasOwnProperty('maxSnakeLen')) {
                obj['maxSnakeLen'] = ApiClient.convertToType(data['maxSnakeLen'], 'Number');
            }
            if (data.hasOwnProperty('heatmapColumns')) {
                obj['heatmapColumns'] = ApiClient.convertToType(data['heatmapColumns'], 'Number');
            }
            if (data.hasOwnProperty('countLineX1')) {
                obj['countLineX1'] = ApiClient.convertToType(data['countLineX1'], 'Number');
            }
            if (data.hasOwnProperty('countLineY1')) {
                obj['countLineY1'] = ApiClient.convertToType(data['countLineY1'], 'Number');
            }
            if (data.hasOwnProperty('countLineX2')) {
                obj['countLineX2'] = ApiClient.convertToType(data['countLineX2'], 'Number');
            }
            if (data.hasOwnProperty('countLineY2')) {
                obj['countLineY2'] = ApiClient.convertToType(data['countLineY2'], 'Number');
            }
            if (data.hasOwnProperty('transformationShapeWidth')) {
                obj['transformationShapeWidth'] = ApiClient.convertToType(data['transformationShapeWidth'], 'Number');
            }
            if (data.hasOwnProperty('transformationShapeHeight')) {
                obj['transformationShapeHeight'] = ApiClient.convertToType(data['transformationShapeHeight'], 'Number');
            }
            if (data.hasOwnProperty('cameraRoiLength')) {
                obj['cameraRoiLength'] = ApiClient.convertToType(data['cameraRoiLength'], 'Number');
            }
            if (data.hasOwnProperty('roiGroundCoverage')) {
                obj['roiGroundCoverage'] = ApiClient.convertToType(data['roiGroundCoverage'], 'Number');
            }
            if (data.hasOwnProperty('speedDivider')) {
                obj['speedDivider'] = ApiClient.convertToType(data['speedDivider'], 'Number');
            }
            if (data.hasOwnProperty('socialDistanceGuideline')) {
                obj['socialDistanceGuideline'] = ApiClient.convertToType(data['socialDistanceGuideline'], 'Number');
            }
            if (data.hasOwnProperty('clearPathsFrameInterval')) {
                obj['clearPathsFrameInterval'] = ApiClient.convertToType(data['clearPathsFrameInterval'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
InsightsGeneratorConfig.prototype['cameraId'] = undefined;

/**
 * @member {String} streamName
 */
InsightsGeneratorConfig.prototype['streamName'] = undefined;

/**
 * @member {Number} resolutionWidth
 */
InsightsGeneratorConfig.prototype['resolutionWidth'] = undefined;

/**
 * @member {Number} resolutionHeight
 */
InsightsGeneratorConfig.prototype['resolutionHeight'] = undefined;

/**
 * @member {Number} cornerMaskX1
 */
InsightsGeneratorConfig.prototype['cornerMaskX1'] = undefined;

/**
 * @member {Number} cornerMaskY1
 */
InsightsGeneratorConfig.prototype['cornerMaskY1'] = undefined;

/**
 * @member {Number} cornerMaskX2
 */
InsightsGeneratorConfig.prototype['cornerMaskX2'] = undefined;

/**
 * @member {Number} cornerMaskY2
 */
InsightsGeneratorConfig.prototype['cornerMaskY2'] = undefined;

/**
 * @member {Number} cornerMaskX3
 */
InsightsGeneratorConfig.prototype['cornerMaskX3'] = undefined;

/**
 * @member {Number} cornerMaskY3
 */
InsightsGeneratorConfig.prototype['cornerMaskY3'] = undefined;

/**
 * @member {Number} cornerMaskX4
 */
InsightsGeneratorConfig.prototype['cornerMaskX4'] = undefined;

/**
 * @member {Number} cornerMaskY4
 */
InsightsGeneratorConfig.prototype['cornerMaskY4'] = undefined;

/**
 * @member {Number} minPointsInPath
 */
InsightsGeneratorConfig.prototype['minPointsInPath'] = undefined;

/**
 * @member {Number} writePathsToDynamo
 */
InsightsGeneratorConfig.prototype['writePathsToDynamo'] = undefined;

/**
 * @member {Number} roundPlaces
 */
InsightsGeneratorConfig.prototype['roundPlaces'] = undefined;

/**
 * @member {Number} maxSnakeLen
 */
InsightsGeneratorConfig.prototype['maxSnakeLen'] = undefined;

/**
 * @member {Number} heatmapColumns
 */
InsightsGeneratorConfig.prototype['heatmapColumns'] = undefined;

/**
 * @member {Number} countLineX1
 */
InsightsGeneratorConfig.prototype['countLineX1'] = undefined;

/**
 * @member {Number} countLineY1
 */
InsightsGeneratorConfig.prototype['countLineY1'] = undefined;

/**
 * @member {Number} countLineX2
 */
InsightsGeneratorConfig.prototype['countLineX2'] = undefined;

/**
 * @member {Number} countLineY2
 */
InsightsGeneratorConfig.prototype['countLineY2'] = undefined;

/**
 * @member {Number} transformationShapeWidth
 */
InsightsGeneratorConfig.prototype['transformationShapeWidth'] = undefined;

/**
 * @member {Number} transformationShapeHeight
 */
InsightsGeneratorConfig.prototype['transformationShapeHeight'] = undefined;

/**
 * @member {Number} cameraRoiLength
 */
InsightsGeneratorConfig.prototype['cameraRoiLength'] = undefined;

/**
 * @member {Number} roiGroundCoverage
 */
InsightsGeneratorConfig.prototype['roiGroundCoverage'] = undefined;

/**
 * @member {Number} speedDivider
 */
InsightsGeneratorConfig.prototype['speedDivider'] = undefined;

/**
 * @member {Number} socialDistanceGuideline
 */
InsightsGeneratorConfig.prototype['socialDistanceGuideline'] = undefined;

/**
 * @member {Number} clearPathsFrameInterval
 */
InsightsGeneratorConfig.prototype['clearPathsFrameInterval'] = undefined;






export default InsightsGeneratorConfig;

