/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TotalCameraSocialDistanceAvg model module.
 * @module model/TotalCameraSocialDistanceAvg
 * @version 1.0.0
 */
class TotalCameraSocialDistanceAvg {
    /**
     * Constructs a new <code>TotalCameraSocialDistanceAvg</code>.
     * A socail distance average for a given day.
     * @alias module:model/TotalCameraSocialDistanceAvg
     * @param cameraId {Number} 
     * @param _date {String} 
     * @param socialDistCompliance {Number} 
     */
    constructor(cameraId, _date, socialDistCompliance) { 
        
        TotalCameraSocialDistanceAvg.initialize(this, cameraId, _date, socialDistCompliance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, _date, socialDistCompliance) { 
        obj['cameraId'] = cameraId;
        obj['date'] = _date;
        obj['socialDistCompliance'] = socialDistCompliance;
    }

    /**
     * Constructs a <code>TotalCameraSocialDistanceAvg</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TotalCameraSocialDistanceAvg} obj Optional instance to populate.
     * @return {module:model/TotalCameraSocialDistanceAvg} The populated <code>TotalCameraSocialDistanceAvg</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TotalCameraSocialDistanceAvg();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('socialDistCompliance')) {
                obj['socialDistCompliance'] = ApiClient.convertToType(data['socialDistCompliance'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
TotalCameraSocialDistanceAvg.prototype['cameraId'] = undefined;

/**
 * @member {String} date
 */
TotalCameraSocialDistanceAvg.prototype['date'] = undefined;

/**
 * @member {Number} socialDistCompliance
 */
TotalCameraSocialDistanceAvg.prototype['socialDistCompliance'] = undefined;






export default TotalCameraSocialDistanceAvg;

