/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TotalCameraWalkingPace model module.
 * @module model/TotalCameraWalkingPace
 * @version 1.0.0
 */
class TotalCameraWalkingPace {
    /**
     * Constructs a new <code>TotalCameraWalkingPace</code>.
     * A walking pace average for a given day.
     * @alias module:model/TotalCameraWalkingPace
     * @param cameraId {Number} 
     * @param _date {String} 
     * @param avgPersonSpeed {Number} 
     */
    constructor(cameraId, _date, avgPersonSpeed) { 
        
        TotalCameraWalkingPace.initialize(this, cameraId, _date, avgPersonSpeed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, _date, avgPersonSpeed) { 
        obj['cameraId'] = cameraId;
        obj['date'] = _date;
        obj['avgPersonSpeed'] = avgPersonSpeed;
    }

    /**
     * Constructs a <code>TotalCameraWalkingPace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TotalCameraWalkingPace} obj Optional instance to populate.
     * @return {module:model/TotalCameraWalkingPace} The populated <code>TotalCameraWalkingPace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TotalCameraWalkingPace();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('avgPersonSpeed')) {
                obj['avgPersonSpeed'] = ApiClient.convertToType(data['avgPersonSpeed'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
TotalCameraWalkingPace.prototype['cameraId'] = undefined;

/**
 * @member {String} date
 */
TotalCameraWalkingPace.prototype['date'] = undefined;

/**
 * @member {Number} avgPersonSpeed
 */
TotalCameraWalkingPace.prototype['avgPersonSpeed'] = undefined;






export default TotalCameraWalkingPace;

