/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TotalCameraTimeSpent model module.
 * @module model/TotalCameraTimeSpent
 * @version 1.0.0
 */
class TotalCameraTimeSpent {
    /**
     * Constructs a new <code>TotalCameraTimeSpent</code>.
     * A time spent average for a given day.
     * @alias module:model/TotalCameraTimeSpent
     * @param cameraId {Number} 
     * @param _date {String} 
     * @param estTimeSpent {Number} 
     */
    constructor(cameraId, _date, estTimeSpent) { 
        
        TotalCameraTimeSpent.initialize(this, cameraId, _date, estTimeSpent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, _date, estTimeSpent) { 
        obj['cameraId'] = cameraId;
        obj['date'] = _date;
        obj['estTimeSpent'] = estTimeSpent;
    }

    /**
     * Constructs a <code>TotalCameraTimeSpent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TotalCameraTimeSpent} obj Optional instance to populate.
     * @return {module:model/TotalCameraTimeSpent} The populated <code>TotalCameraTimeSpent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TotalCameraTimeSpent();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('estTimeSpent')) {
                obj['estTimeSpent'] = ApiClient.convertToType(data['estTimeSpent'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
TotalCameraTimeSpent.prototype['cameraId'] = undefined;

/**
 * @member {String} date
 */
TotalCameraTimeSpent.prototype['date'] = undefined;

/**
 * @member {Number} estTimeSpent
 */
TotalCameraTimeSpent.prototype['estTimeSpent'] = undefined;






export default TotalCameraTimeSpent;

