/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TotalCameraDensity model module.
 * @module model/TotalCameraDensity
 * @version 1.0.0
 */
class TotalCameraDensity {
    /**
     * Constructs a new <code>TotalCameraDensity</code>.
     * A density average for a given day.
     * @alias module:model/TotalCameraDensity
     * @param cameraId {Number} 
     * @param _date {String} 
     * @param density {Number} 
     */
    constructor(cameraId, _date, density) { 
        
        TotalCameraDensity.initialize(this, cameraId, _date, density);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, _date, density) { 
        obj['cameraId'] = cameraId;
        obj['date'] = _date;
        obj['density'] = density;
    }

    /**
     * Constructs a <code>TotalCameraDensity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TotalCameraDensity} obj Optional instance to populate.
     * @return {module:model/TotalCameraDensity} The populated <code>TotalCameraDensity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TotalCameraDensity();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('density')) {
                obj['density'] = ApiClient.convertToType(data['density'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cameraId
 */
TotalCameraDensity.prototype['cameraId'] = undefined;

/**
 * @member {String} date
 */
TotalCameraDensity.prototype['date'] = undefined;

/**
 * @member {Number} density
 */
TotalCameraDensity.prototype['density'] = undefined;






export default TotalCameraDensity;

