/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StreetseekServer);
  }
}(this, function(expect, StreetseekServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StreetseekServer.CameraCaptureApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CameraCaptureApi', function() {
    describe('cameraCapturePersonCountDateByHourGet', function() {
      it('should call cameraCapturePersonCountDateByHourGet successfully', function(done) {
        //uncomment below and update the code to test cameraCapturePersonCountDateByHourGet
        //instance.cameraCapturePersonCountDateByHourGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cameraCapturePersonCountDateMinuteIntervalIntervalGet', function() {
      it('should call cameraCapturePersonCountDateMinuteIntervalIntervalGet successfully', function(done) {
        //uncomment below and update the code to test cameraCapturePersonCountDateMinuteIntervalIntervalGet
        //instance.cameraCapturePersonCountDateMinuteIntervalIntervalGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cameraCapturePersonCountTotalForDayDateByCameraIdCameraIdGet', function() {
      it('should call cameraCapturePersonCountTotalForDayDateByCameraIdCameraIdGet successfully', function(done) {
        //uncomment below and update the code to test cameraCapturePersonCountTotalForDayDateByCameraIdCameraIdGet
        //instance.cameraCapturePersonCountTotalForDayDateByCameraIdCameraIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cameraCapturePersonCountTotalPerDayBetweenDatesStartStartDateEndEndDateForCameraCameraIdGet', function() {
      it('should call cameraCapturePersonCountTotalPerDayBetweenDatesStartStartDateEndEndDateForCameraCameraIdGet successfully', function(done) {
        //uncomment below and update the code to test cameraCapturePersonCountTotalPerDayBetweenDatesStartStartDateEndEndDateForCameraCameraIdGet
        //instance.cameraCapturePersonCountTotalPerDayBetweenDatesStartStartDateEndEndDateForCameraCameraIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cameraCaptureUploadCapturePost', function() {
      it('should call cameraCaptureUploadCapturePost successfully', function(done) {
        //uncomment below and update the code to test cameraCaptureUploadCapturePost
        //instance.cameraCaptureUploadCapturePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
