/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InsightsGeneratorConfig from '../model/InsightsGeneratorConfig';

/**
* CameraInsightGenerator service.
* @module api/CameraInsightGeneratorApi
* @version 1.0.0
*/
export default class CameraInsightGeneratorApi {

    /**
    * Constructs a new CameraInsightGeneratorApi. 
    * @alias module:api/CameraInsightGeneratorApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {String} streamName 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InsightsGeneratorConfig} and HTTP response
     */
    cameraInsightGeneratorConfigByStreamNameStreamNameGetWithHttpInfo(streamName) {
      let postBody = null;
      // verify the required parameter 'streamName' is set
      if (streamName === undefined || streamName === null) {
        throw new Error("Missing the required parameter 'streamName' when calling cameraInsightGeneratorConfigByStreamNameStreamNameGet");
      }

      let pathParams = {
        'streamName': streamName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InsightsGeneratorConfig;
      return this.apiClient.callApi(
        '/camera-insight-generator/config/by/stream-name/{streamName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} streamName 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InsightsGeneratorConfig}
     */
    cameraInsightGeneratorConfigByStreamNameStreamNameGet(streamName) {
      return this.cameraInsightGeneratorConfigByStreamNameStreamNameGetWithHttpInfo(streamName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
