/**
 * Streetseek Server
 * streetseek.server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StreetseekServer);
  }
}(this, function(expect, StreetseekServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StreetseekServer.CameraInsights();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CameraInsights', function() {
    it('should create an instance of CameraInsights', function() {
      // uncomment below and update the code to test CameraInsights
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be.a(StreetseekServer.CameraInsights);
    });

    it('should have the property cameraId (base name: "cameraId")', function() {
      // uncomment below and update the code to test the property cameraId
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property startFrameTime (base name: "startFrameTime")', function() {
      // uncomment below and update the code to test the property startFrameTime
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property endFrameTime (base name: "endFrameTime")', function() {
      // uncomment below and update the code to test the property endFrameTime
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property personCount (base name: "personCount")', function() {
      // uncomment below and update the code to test the property personCount
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property personCountRight (base name: "personCountRight")', function() {
      // uncomment below and update the code to test the property personCountRight
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property personCountLeft (base name: "personCountLeft")', function() {
      // uncomment below and update the code to test the property personCountLeft
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property avgPersonSpeed (base name: "avgPersonSpeed")', function() {
      // uncomment below and update the code to test the property avgPersonSpeed
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property estTimeSpent (base name: "estTimeSpent")', function() {
      // uncomment below and update the code to test the property estTimeSpent
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property socialDistCompliance (base name: "socialDistCompliance")', function() {
      // uncomment below and update the code to test the property socialDistCompliance
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property medianDensity (base name: "medianDensity")', function() {
      // uncomment below and update the code to test the property medianDensity
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

    it('should have the property heatmap (base name: "heatmap")', function() {
      // uncomment below and update the code to test the property heatmap
      //var instane = new StreetseekServer.CameraInsights();
      //expect(instance).to.be();
    });

  });

}));
