AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  trackerstreetseek:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 3008
      Timeout: 60
      Role: >-
        arn:aws:iam::439151388240:role/service-role/tracker-streetseek-role-1k67eue2
      Layers:
        - >-
          arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python37-SciPy1x:22
        - 'arn:aws:lambda:eu-west-1:439151388240:layer:python_filterpy:1'
        - 'arn:aws:lambda:eu-west-1:439151388240:layer:python_opencv:1'
