AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  streetseekstackLambdaFunction125B1IORLS6TB:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::439151388240:role/streetseek-stack-LambdaRole-A8X2Y6FVJ524'
      Events:
        Kinesis1:
          Type: Kinesis
          Properties:
            Stream:
              'Fn::GetAtt':
                - KinesisStream1
                - Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
  KinesisStream1:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      ShardCount: 1
